namespace Prototype.Components.Pages.Product.Webcat;

public static class WebcatSeedData
{
    public static List<WebcatItem> GetItems()
    {
        var items = new List<WebcatItem>();

        // ============================================================
        // ITEMS FROM ITEMS ON ORDER (so side panel will show data)
        // ============================================================

        // CQT Stock items from Items on Order
        items.AddRange(new[]
        {
            new WebcatItem
            {
                Item = "A02",
                Description = "1/4\" Drive (F) x 3/8\" (M) Adapter",
                ListPrice = 23.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "Adapters",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 15,
                Pending = 2,
                OnOrder = 1,
                Alloc = 0,
                BKO = 1,
                InTransit = 0,
                Needs = 0,
                Interests = 3,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 23.50m,
                CatalogText = "Professional-grade drive adapter. Converts 1/4\" female to 3/8\" male. Lifetime warranty on workmanship."
            },
            new WebcatItem
            {
                Item = "A20",
                Description = "3/8\" Drive (F) x 1/2\" (M) Adapter",
                ListPrice = 45.00m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "Adapters",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 8,
                Pending = 0,
                OnOrder = 2,
                Alloc = 0,
                BKO = 0,
                InTransit = 2,
                Needs = 0,
                Interests = 5,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 45.00m,
                CatalogText = "Heavy-duty adapter for converting 3/8\" female drive to 1/2\" male. Chrome vanadium steel construction."
            },
            new WebcatItem
            {
                Item = "A23",
                Description = "3/8\" Drive (F) x 1/2\" (M) Adapter",
                ListPrice = 22.10m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "Adapters",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 12,
                Pending = 1,
                OnOrder = 1,
                Alloc = 0,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 2,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 22.10m,
                CatalogText = "Compact 3/8\" to 1/2\" adapter with ball detent. Corrosion-resistant finish."
            },
            new WebcatItem
            {
                Item = "A35",
                Description = "1/2\" Drive (F) x 3/4\" (M) Adapter",
                ListPrice = 18.75m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "Adapters",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 6,
                Pending = 0,
                OnOrder = 1,
                Alloc = 0,
                BKO = 0,
                InTransit = 0,
                Needs = 2,
                Interests = 1,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 18.75m,
                CatalogText = "Industrial-strength 1/2\" to 3/4\" drive adapter. Ideal for heavy-duty applications."
            },
            new WebcatItem
            {
                Item = "AF12201",
                Description = "1220-1 AIR TOOL OIL PINT",
                ListPrice = 10.00m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "Consumable",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Fluids & Lubricants",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 45,
                Pending = 8,
                OnOrder = 18,
                Alloc = 0,
                BKO = 0,
                InTransit = 18,
                Needs = 0,
                Interests = 25,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 10.00m,
                CatalogText = "Premium air tool oil in pint size. Keeps pneumatic tools running smoothly and extends their life."
            },
            new WebcatItem
            {
                Item = "AP328",
                Description = "1/2\"Dr.(F) x 1/2\"(M) Imp Adapt,Ball Type",
                ListPrice = 19.30m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "Adapters",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 9,
                Pending = 0,
                OnOrder = 1,
                Alloc = 0,
                BKO = 0,
                InTransit = 1,
                Needs = 0,
                Interests = 2,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 19.30m,
                CatalogText = "Impact-rated ball-type adapter for 1/2\" drive. Designed for use with impact wrenches."
            },
            new WebcatItem
            {
                Item = "AS6SB",
                Description = "Stubby Air Slide Hammer",
                ListPrice = 159.99m,
                Discount = "B",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Body Tools",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 4,
                Pending = 0,
                OnOrder = 1,
                Alloc = 0,
                BKO = 0,
                InTransit = 1,
                Needs = 0,
                Interests = 3,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 159.99m,
                CatalogText = "Pneumatic slide hammer perfect for dent removal and panel work. Compact stubby design for tight spaces."
            },
            new WebcatItem
            {
                Item = "CAT3160",
                Description = "3/16\" Orbital Sander 6\"",
                ListPrice = 299.00m,
                Discount = "B",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Power Tools",
                Subcategory = "Sanders",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 3,
                Pending = 1,
                OnOrder = 1,
                Alloc = 0,
                BKO = 1,
                InTransit = 2,
                Needs = 0,
                Interests = 4,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 299.00m,
                CatalogText = "Professional 6-inch orbital sander with 3/16\" orbit. Perfect for body work and finishing."
            },
            new WebcatItem
            {
                Item = "B450",
                Description = "1/2\" Impact Socket Set, 15pc",
                ListPrice = 189.99m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Sockets",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 18,
                Pending = 2,
                OnOrder = 5,
                Alloc = 2,
                BKO = 0,
                InTransit = 3,
                Needs = 0,
                Interests = 12,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 189.99m,
                CatalogText = "15-piece 1/2\" drive impact socket set. Chrome molybdenum steel with black oxide finish. Includes carrying case."
            },
            new WebcatItem
            {
                Item = "B451",
                Description = "3/8\" Deep Socket Set, 12pc",
                ListPrice = 145.50m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Sockets",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 12,
                Pending = 1,
                OnOrder = 3,
                Alloc = 1,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 8,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 145.50m,
                CatalogText = "12-piece 3/8\" drive deep socket set. Metric sizes perfect for reaching recessed fasteners."
            },
            new WebcatItem
            {
                Item = "C120",
                Description = "Torque Wrench 1/2\" Drive 50-250 ft-lb",
                ListPrice = 425.00m,
                Discount = "C",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                IsPriceConfirm = true,
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 5,
                Pending = 0,
                OnOrder = 2,
                Alloc = 0,
                BKO = 2,
                InTransit = 0,
                Needs = 2,
                Interests = 6,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 425.00m,
                CatalogText = "Professional 1/2\" drive click-type torque wrench. 50-250 ft-lb range with dual-scale markings. Includes calibration certificate."
            },
            new WebcatItem
            {
                Item = "C125",
                Description = "Digital Torque Adapter 1/4\" Drive",
                ListPrice = 275.00m,
                Discount = "TECH",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 8,
                Pending = 1,
                OnOrder = 4,
                Alloc = 1,
                BKO = 1,
                InTransit = 2,
                Needs = 0,
                Interests = 7,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 275.00m,
                CatalogText = "Digital torque adapter with LCD display. 1/4\" drive, measures 5-100 ft-lbs with +/- 2% accuracy."
            },
            new WebcatItem
            {
                Item = "D330",
                Description = "Ratcheting Wrench Set SAE 10pc",
                ListPrice = 195.00m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 22,
                Pending = 2,
                OnOrder = 6,
                Alloc = 1,
                BKO = 1,
                InTransit = 4,
                Needs = 0,
                Interests = 15,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 195.00m,
                CatalogText = "10-piece SAE ratcheting combination wrench set. 72-tooth mechanism for 5-degree arc swing. Sizes 1/4\" to 3/4\"."
            },
            new WebcatItem
            {
                Item = "D335",
                Description = "Ratcheting Wrench Set Metric 10pc",
                ListPrice = 195.00m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 19,
                Pending = 1,
                OnOrder = 5,
                Alloc = 2,
                BKO = 0,
                InTransit = 3,
                Needs = 0,
                Interests = 13,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 195.00m,
                CatalogText = "10-piece metric ratcheting combination wrench set. 72-tooth mechanism. Sizes 8mm to 19mm."
            },
            new WebcatItem
            {
                Item = "E440",
                Description = "Pliers Set 4pc",
                ListPrice = 89.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Pliers",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 28,
                Pending = 4,
                OnOrder = 8,
                Alloc = 2,
                BKO = 0,
                InTransit = 6,
                Needs = 0,
                Interests = 11,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 89.99m,
                CatalogText = "4-piece pliers set including needle nose, slip joint, diagonal cutters, and linesman pliers."
            },
            new WebcatItem
            {
                Item = "E445",
                Description = "Diagonal Cutters 8\"",
                ListPrice = 45.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Pliers",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 34,
                Pending = 6,
                OnOrder = 12,
                Alloc = 1,
                BKO = 1,
                InTransit = 10,
                Needs = 0,
                Interests = 18,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 45.50m,
                CatalogText = "Professional 8\" diagonal cutting pliers. Induction-hardened cutting edges. Cushion grip handles."
            },
            new WebcatItem
            {
                Item = "F550",
                Description = "Screwdriver Set 10pc",
                ListPrice = 67.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Screwdrivers",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 42,
                Pending = 5,
                OnOrder = 10,
                Alloc = 2,
                BKO = 0,
                InTransit = 8,
                Needs = 0,
                Interests = 14,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 67.99m,
                CatalogText = "10-piece screwdriver set with Phillips and flathead. Chrome vanadium steel shafts with comfort grip handles."
            },
            new WebcatItem
            {
                Item = "F555",
                Description = "Precision Screwdriver Set 6pc",
                ListPrice = 34.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Screwdrivers",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 56,
                Pending = 8,
                OnOrder = 15,
                Alloc = 3,
                BKO = 0,
                InTransit = 12,
                Needs = 0,
                Interests = 22,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 34.99m,
                CatalogText = "6-piece precision screwdriver set for electronics and small appliances. Includes storage case."
            },
            new WebcatItem
            {
                Item = "G660",
                Description = "Ball Peen Hammer 24oz",
                ListPrice = 42.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Hammers",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 14,
                Pending = 1,
                OnOrder = 4,
                Alloc = 1,
                BKO = 1,
                InTransit = 2,
                Needs = 0,
                Interests = 6,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 42.50m,
                CatalogText = "24-ounce ball peen hammer with hickory handle. Forged steel head with polished striking face."
            },
            new WebcatItem
            {
                Item = "G665",
                Description = "Dead Blow Hammer 3lb",
                ListPrice = 58.99m,
                Discount = "A",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Hammers",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 11,
                Pending = 0,
                OnOrder = 3,
                Alloc = 1,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 5,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 58.99m,
                CatalogText = "3-pound dead blow hammer with polyurethane head. Steel shot-filled to reduce bounce. Comfortable textured grip."
            },
            new WebcatItem
            {
                Item = "H770",
                Description = "Mechanic's Gloves XL",
                ListPrice = 24.99m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "Consumable",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Safety Gear",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Mechanix Wear",
                Supplier = "Mechanix Wear",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 65,
                Pending = 10,
                OnOrder = 20,
                Alloc = 5,
                BKO = 0,
                InTransit = 15,
                Needs = 0,
                Interests = 35,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 24.99m,
                CatalogText = "Mechanix Wear original gloves in XL. Durable synthetic leather palm with breathable TrekDry material."
            },
            new WebcatItem
            {
                Item = "H775",
                Description = "Mechanic's Gloves L",
                ListPrice = 24.99m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "Consumable",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Safety Gear",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Mechanix Wear",
                Supplier = "Mechanix Wear",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 58,
                Pending = 9,
                OnOrder = 18,
                Alloc = 4,
                BKO = 0,
                InTransit = 14,
                Needs = 0,
                Interests = 30,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 24.99m,
                CatalogText = "Mechanix Wear original gloves in Large. Same great quality and protection as XL size."
            },
            new WebcatItem
            {
                Item = "J880",
                Description = "Shop Towels (Box of 200)",
                ListPrice = 15.99m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "Consumable",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Shop Supplies",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 85,
                Pending = 15,
                OnOrder = 25,
                Alloc = 5,
                BKO = 0,
                InTransit = 20,
                Needs = 0,
                Interests = 45,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 15.99m,
                CatalogText = "Industrial-strength shop towels. Box of 200 disposable towels. Absorbent and durable."
            },
            new WebcatItem
            {
                Item = "J885",
                Description = "Parts Cleaner Spray 16oz",
                ListPrice = 12.50m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "Consumable",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Shop Supplies",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 95,
                Pending = 18,
                OnOrder = 30,
                Alloc = 5,
                BKO = 0,
                InTransit = 25,
                Needs = 0,
                Interests = 50,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 12.50m,
                CatalogText = "Heavy-duty parts cleaner spray. 16-ounce aerosol. Quickly removes grease, oil, and grime."
            },
            new WebcatItem
            {
                Item = "K990",
                Description = "Creeper Low Profile",
                ListPrice = 125.00m,
                Discount = "B",
                Warranty = "90 Days",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Storage",
                Subcategory = "Shop Equipment",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 4,
                Pending = 0,
                OnOrder = 2,
                Alloc = 0,
                BKO = 2,
                InTransit = 0,
                Needs = 2,
                Interests = 4,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 125.00m,
                CatalogText = "Low-profile mechanic's creeper with 6 swivel casters. Padded headrest and oil-resistant vinyl surface."
            },
            new WebcatItem
            {
                Item = "K995",
                Description = "Mechanic's Stool Adjustable",
                ListPrice = 89.99m,
                Discount = "B",
                Warranty = "90 Days",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Storage",
                Subcategory = "Shop Equipment",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 7,
                Pending = 1,
                OnOrder = 3,
                Alloc = 1,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 5,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 89.99m,
                CatalogText = "Adjustable mechanic's stool with pneumatic lift. 300-lb capacity with 5-wheel caster base."
            },
            new WebcatItem
            {
                Item = "M100",
                Description = "Oil Filter Wrench Set 3pc",
                ListPrice = 45.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 24,
                Pending = 3,
                OnOrder = 6,
                Alloc = 2,
                BKO = 0,
                InTransit = 4,
                Needs = 0,
                Interests = 10,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 45.99m,
                CatalogText = "3-piece oil filter wrench set. Includes small, medium, and large sizes. Swivel handles for easy access."
            },
            new WebcatItem
            {
                Item = "M105",
                Description = "Brake Caliper Tool Kit",
                ListPrice = 156.00m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 9,
                Pending = 1,
                OnOrder = 4,
                Alloc = 1,
                BKO = 1,
                InTransit = 2,
                Needs = 0,
                Interests = 7,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 156.00m,
                CatalogText = "Complete brake caliper tool kit. Includes piston retracting tool and adapters for most vehicles."
            },
            new WebcatItem
            {
                Item = "N200",
                Description = "Battery Terminal Cleaner",
                ListPrice = 18.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 32,
                Pending = 4,
                OnOrder = 8,
                Alloc = 2,
                BKO = 0,
                InTransit = 6,
                Needs = 0,
                Interests = 12,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 18.50m,
                CatalogText = "Battery terminal cleaning tool with wire brush. Cleans both post and clamp terminals."
            },
            new WebcatItem
            {
                Item = "N205",
                Description = "Circuit Tester 12V-24V",
                ListPrice = 28.99m,
                Discount = "A",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Diagnostics",
                Subcategory = "Meters",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 38,
                Pending = 5,
                OnOrder = 10,
                Alloc = 2,
                BKO = 0,
                InTransit = 8,
                Needs = 0,
                Interests = 15,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 28.99m,
                CatalogText = "12V-24V circuit tester with LED indicator. Heavy-duty probe tip and grounding clamp."
            },
            new WebcatItem
            {
                Item = "P300",
                Description = "Magnetic Parts Tray 6\"",
                ListPrice = 14.99m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "Consumable",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Shop Supplies",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 48,
                Pending = 7,
                OnOrder = 12,
                Alloc = 2,
                BKO = 0,
                InTransit = 10,
                Needs = 0,
                Interests = 20,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 14.99m,
                CatalogText = "6-inch magnetic parts tray. Stainless steel construction. Keeps small parts organized and secure."
            },
            new WebcatItem
            {
                Item = "P305",
                Description = "Magnetic Pick-Up Tool Telescoping",
                ListPrice = 19.99m,
                Discount = "A",
                Warranty = "90 Days",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Shop Supplies",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 54,
                Pending = 8,
                OnOrder = 15,
                Alloc = 3,
                BKO = 0,
                InTransit = 12,
                Needs = 0,
                Interests = 25,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 19.99m,
                CatalogText = "Telescoping magnetic pick-up tool. Extends up to 24 inches. 5-lb lifting capacity."
            },
        });

        // Local Only Items from Items on Order
        items.AddRange(new[]
        {
            new WebcatItem
            {
                Item = "LPN-RW7M",
                Description = "Ratcheting Wrench 7mm",
                ListPrice = 28.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 6,
                Pending = 0,
                OnOrder = 2,
                Alloc = 1,
                BKO = 1,
                InTransit = 0,
                Needs = 0,
                Interests = 3,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 28.50m,
                CatalogText = "7mm ratcheting combination wrench. 72-tooth mechanism for tight spaces."
            },
            new WebcatItem
            {
                Item = "LPN-1002",
                Description = "Specialty Socket 32mm Deep",
                ListPrice = 45.00m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Sockets",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 3,
                Pending = 0,
                OnOrder = 1,
                Alloc = 0,
                BKO = 1,
                InTransit = 0,
                Needs = 1,
                Interests = 2,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 45.00m,
                CatalogText = "32mm deep impact socket. 1/2\" drive, 6-point design for heavy-duty applications."
            },
            new WebcatItem
            {
                Item = "LPN-BC45",
                Description = "Brake Caliper Piston Tool",
                ListPrice = 67.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 5,
                Pending = 1,
                OnOrder = 3,
                Alloc = 1,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 4,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 67.50m,
                CatalogText = "Universal brake caliper piston rewind tool. Works with most disc brake calipers."
            },
            new WebcatItem
            {
                Item = "LPN-TW250",
                Description = "Torque Wrench 3/8\" Drive 25-250 in-lb",
                ListPrice = 189.99m,
                Discount = "B",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 4,
                Pending = 0,
                OnOrder = 2,
                Alloc = 1,
                BKO = 1,
                InTransit = 0,
                Needs = 1,
                Interests = 3,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 189.99m,
                CatalogText = "3/8\" drive click-type torque wrench. 25-250 inch-pound range. Perfect for smaller fasteners."
            },
            new WebcatItem
            {
                Item = "LPN-HS12",
                Description = "Hose Clamp Pliers Set",
                ListPrice = 54.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Pliers",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 8,
                Pending = 1,
                OnOrder = 4,
                Alloc = 1,
                BKO = 1,
                InTransit = 2,
                Needs = 0,
                Interests = 5,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 54.99m,
                CatalogText = "Hose clamp pliers with swivel jaws. Includes multiple tips for different clamp styles."
            },
            new WebcatItem
            {
                Item = "LPN-PB20",
                Description = "Pry Bar Set 3pc",
                ListPrice = 39.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 12,
                Pending = 2,
                OnOrder = 5,
                Alloc = 2,
                BKO = 0,
                InTransit = 3,
                Needs = 0,
                Interests = 7,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 39.99m,
                CatalogText = "3-piece pry bar set. Forged steel construction with different angles for various applications."
            },
            new WebcatItem
            {
                Item = "LPN-CH80",
                Description = "Chisel Set 8pc",
                ListPrice = 48.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 7,
                Pending = 1,
                OnOrder = 3,
                Alloc = 1,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 4,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 48.50m,
                CatalogText = "8-piece cold chisel set. Heat-treated alloy steel. Includes flat, diamond point, and cape chisels."
            },
            new WebcatItem
            {
                Item = "LPN-FB15",
                Description = "File Set 5pc with Handle",
                ListPrice = 32.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 14,
                Pending = 2,
                OnOrder = 6,
                Alloc = 2,
                BKO = 0,
                InTransit = 4,
                Needs = 0,
                Interests = 8,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 32.99m,
                CatalogText = "5-piece file set with comfortable handle. Includes flat, half-round, round, square, and triangular files."
            },
            new WebcatItem
            {
                Item = "LPN-TH25",
                Description = "Thread Repair Kit M10 x 1.5",
                ListPrice = 78.00m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "Consumable",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 6,
                Pending = 0,
                OnOrder = 2,
                Alloc = 1,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 3,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 78.00m,
                CatalogText = "M10 x 1.5 thread repair kit. Includes tap, inserts, and installation tool."
            },
            new WebcatItem
            {
                Item = "LPN-OT40",
                Description = "Oil Filter Cap Wrench 74mm",
                ListPrice = 24.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 10,
                Pending = 1,
                OnOrder = 4,
                Alloc = 2,
                BKO = 0,
                InTransit = 2,
                Needs = 0,
                Interests = 6,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 24.99m,
                CatalogText = "74mm oil filter cap wrench. 15-flute design fits most cartridge-style oil filters."
            },
            new WebcatItem
            {
                Item = "LPN-ST60",
                Description = "Spark Plug Socket Set 3pc",
                ListPrice = 42.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Sockets",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 11,
                Pending = 2,
                OnOrder = 5,
                Alloc = 1,
                BKO = 1,
                InTransit = 3,
                Needs = 0,
                Interests = 7,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 42.50m,
                CatalogText = "3-piece spark plug socket set. Includes 5/8\", 13/16\", and 3/4\" with magnetic inserts."
            },
            new WebcatItem
            {
                Item = "LPN-FL90",
                Description = "Flashlight LED Rechargeable",
                ListPrice = 45.99m,
                Discount = "A",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Shop Supplies",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 18,
                Pending = 3,
                OnOrder = 8,
                Alloc = 2,
                BKO = 0,
                InTransit = 6,
                Needs = 0,
                Interests = 12,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 45.99m,
                CatalogText = "Rechargeable LED flashlight. 1000 lumens. USB charging with battery indicator."
            },
            new WebcatItem
            {
                Item = "LPN-MT55",
                Description = "Multimeter Digital Auto-Ranging",
                ListPrice = 89.99m,
                Discount = "A",
                Warranty = "2 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Diagnostics",
                Subcategory = "Meters",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 7,
                Pending = 1,
                OnOrder = 3,
                Alloc = 1,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 5,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 89.99m,
                CatalogText = "Auto-ranging digital multimeter. Measures AC/DC voltage, current, resistance, and continuity."
            },
            new WebcatItem
            {
                Item = "LPN-WR35",
                Description = "Wire Stripper/Crimper Tool",
                ListPrice = 36.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 13,
                Pending = 2,
                OnOrder = 6,
                Alloc = 2,
                BKO = 0,
                InTransit = 4,
                Needs = 0,
                Interests = 9,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 36.50m,
                CatalogText = "Professional wire stripper and crimper. Handles 10-22 AWG wire. Built-in wire cutter."
            },
            new WebcatItem
            {
                Item = "LPN-VG22",
                Description = "Vacuum Pump & Gauge Kit",
                ListPrice = 156.00m,
                Discount = "B",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Diagnostics",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 3,
                Pending = 0,
                OnOrder = 1,
                Alloc = 0,
                BKO = 1,
                InTransit = 0,
                Needs = 1,
                Interests = 2,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 156.00m,
                CatalogText = "Hand-operated vacuum pump with gauge. Perfect for brake bleeding and testing vacuum systems."
            },
            new WebcatItem
            {
                Item = "LPN-AR18",
                Description = "A/C Service Hose Set",
                ListPrice = 124.99m,
                Discount = "B",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Diagnostics",
                Subcategory = "Specialty Tools",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 4,
                Pending = 1,
                OnOrder = 2,
                Alloc = 0,
                BKO = 1,
                InTransit = 1,
                Needs = 0,
                Interests = 3,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 124.99m,
                CatalogText = "A/C service hose set with quick couplers. Compatible with R-134a and R-1234yf systems."
            },
        });

        return items;
    }

    public sealed class WebcatItem
    {
        public string Item { get; set; } = "";
        public string Description { get; set; } = "";
        public decimal ListPrice { get; set; }
        public string Discount { get; set; } = "A";
        public string Warranty { get; set; } = "";
        public string Action { get; set; } = "";
        public string Status { get; set; } = "";
        public string Category { get; set; } = "";
        public string Subcategory { get; set; } = "";
        public string Class { get; set; } = "";
        public string ShipFrom { get; set; } = "";
        public string Brand { get; set; } = "";
        public string Supplier { get; set; } = "";
        public string ReplacedBy { get; set; } = "";
        public int BuyQty { get; set; }
        public int SellQty { get; set; }

        public int OnHand { get; set; }
        public int Pending { get; set; }
        public int OnOrder { get; set; }
        public int Alloc { get; set; }
        public int BKO { get; set; }
        public int InTransit { get; set; }
        public int Needs { get; set; }
        public int Interests { get; set; }

        public DateTime? EffectiveDate { get; set; }
        public decimal LocalListPrice { get; set; }
        public string CatalogText { get; set; } = "";

        public bool IsDiscontinued { get; set; }
        public bool IsPriceConfirm { get; set; }
        public bool IsCSI { get; set; }
        public bool IsDropShip { get; set; }
        public bool IsSpecialOrder { get; set; }
    }
}