namespace Prototype.Components.Pages.Product.Webcat;

public static class WebcatSeedData
{
    public static List<WebcatItem> GetItems()
    {
        var random = new Random(42); // Fixed seed for consistent data

        var items = new List<WebcatItem>
        {
            // Drive Tools - 3/8" Ratchets
            new WebcatItem
            {
                Item = "1/4",
                Description = "1/4\" Ball (25-Pack)",
                ListPrice = 5.09m,
                Discount = "A",
                Warranty = "10",
                Action = "No Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "3/8\" Ratchets",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 12,
                Pending = 0,
                OnOrder = 25,
                Alloc = 2,
                BKO = 0,
                InTransit = 5,
                Needs = 0,
                Interests = 3,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 5.09m,
                CatalogText = "High-quality 1/4\" ball bearing set. Perfect for precision work."
            },
            new WebcatItem
            {
                Item = "1/8",
                Description = "1/8\" Ball Bearing",
                ListPrice = 4.25m,
                Discount = "A",
                Warranty = "10",
                Action = "No Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "3/8\" Ratchets",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 8,
                Pending = 2,
                OnOrder = 0,
                Alloc = 1,
                BKO = 0,
                InTransit = 0,
                Needs = 5,
                Interests = 2,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 4.25m,
                CatalogText = "Precision 1/8\" ball bearings for light-duty applications."
            },
            new WebcatItem
            {
                Item = "CR38R",
                Description = "3/8\" Ratchet - 72 Tooth",
                ListPrice = 149.99m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "3/8\" Ratchets",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 45,
                Pending = 5,
                OnOrder = 20,
                Alloc = 8,
                BKO = 0,
                InTransit = 10,
                Needs = 0,
                Interests = 12,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 149.99m,
                CatalogText = "Professional-grade 3/8\" drive ratchet with 72-tooth mechanism for superior performance."
            },

            // Drive Tools - 1/2" Ratchets
            new WebcatItem
            {
                Item = "CR12R",
                Description = "1/2\" Ratchet - Heavy Duty",
                ListPrice = 189.99m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "1/2\" Ratchets",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 32,
                Pending = 3,
                OnOrder = 15,
                Alloc = 5,
                BKO = 0,
                InTransit = 8,
                Needs = 0,
                Interests = 7,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 189.99m,
                CatalogText = "Heavy-duty 1/2\" drive ratchet. Built for the toughest jobs."
            },

            // Hand Tools - Wrenches (Cornwell Brand)
            new WebcatItem
            {
                Item = "CW-SET10M",
                Description = "Combination Wrench Set 10pc Metric",
                ListPrice = 189.99m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 32,
                Pending = 5,
                OnOrder = 15,
                Alloc = 8,
                BKO = 0,
                InTransit = 7,
                Needs = 0,
                Interests = 12,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 189.99m,
                CatalogText = "Complete 10-piece metric combination wrench set. Premium chrome vanadium steel."
            },
            new WebcatItem
            {
                Item = "LPN-1003",
                Description = "Adjustable Wrench 12\" (Discontinued)",
                ListPrice = 45.50m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Discontinued",
                IsDiscontinued = true,
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                ReplacedBy = "CW-ADJ12",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 3,
                Pending = 0,
                OnOrder = 0,
                Alloc = 0,
                BKO = 0,
                InTransit = 0,
                Needs = 0,
                Interests = 0,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 45.50m,
                CatalogText = "DISCONTINUED - See item CW-ADJ12 for replacement."
            },
            new WebcatItem
            {
                Item = "CFWS10MM",
                Description = "10mm Flex Head Ratcheting Wrench",
                ListPrice = 34.99m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 67,
                Pending = 8,
                OnOrder = 30,
                Alloc = 12,
                BKO = 0,
                InTransit = 15,
                Needs = 0,
                Interests = 18,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 34.99m,
                CatalogText = "Flex head ratcheting combination wrench. 180-degree flex head for hard-to-reach areas."
            },

            // Hand Tools - Sockets (Cornwell Brand)
            new WebcatItem
            {
                Item = "S38SET-42",
                Description = "3/8\" Socket Set 42pc Metric",
                ListPrice = 299.99m,
                Discount = "C",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Sockets",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 24,
                Pending = 4,
                OnOrder = 10,
                Alloc = 6,
                BKO = 0,
                InTransit = 5,
                Needs = 0,
                Interests = 9,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 299.99m,
                CatalogText = "Complete 42-piece 3/8\" drive metric socket set with carrying case."
            },
            new WebcatItem
            {
                Item = "S19MM-DEEP",
                Description = "19mm Deep Impact Socket 1/2\" Drive",
                ListPrice = 18.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Sockets",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 156,
                Pending = 12,
                OnOrder = 50,
                Alloc = 28,
                BKO = 0,
                InTransit = 25,
                Needs = 0,
                Interests = 35,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 18.99m,
                CatalogText = "Heavy-duty 19mm deep impact socket. 1/2\" drive, 6-point design."
            },

            // Storage (Cornwell Brand)
            new WebcatItem
            {
                Item = "10030A25E717",
                Description = "Tool Box Lock Assembly",
                ListPrice = 125.00m,
                Discount = "A",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                IsPriceConfirm = true,
                Category = "Storage",
                Subcategory = "Tool Boxes",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 15,
                Pending = 2,
                OnOrder = 8,
                Alloc = 3,
                BKO = 0,
                InTransit = 4,
                Needs = 0,
                Interests = 4,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 125.00m,
                CatalogText = "Premium lock assembly for Cornwell tool boxes. Includes keys and mounting hardware."
            },
            new WebcatItem
            {
                Item = "CTBR7219",
                Description = "72\" Rolling Tool Cabinet - Black",
                ListPrice = 4599.99m,
                Discount = "PROMO",
                Warranty = "5 Year",
                Action = "Limited Warranty",
                Status = "Active",
                IsDropShip = true,
                Category = "Storage",
                Subcategory = "Tool Boxes",
                Class = "CQT Stock",
                ShipFrom = "2DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 2,
                Pending = 1,
                OnOrder = 3,
                Alloc = 1,
                BKO = 0,
                InTransit = 2,
                Needs = 0,
                Interests = 5,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 4599.99m,
                CatalogText = "Professional 72\" rolling tool cabinet with 19 drawers. Heavy-duty construction with soft-close drawers."
            },

            // Power Tools - Milwaukee Brand
            new WebcatItem
            {
                Item = "MIL-2767-20",
                Description = "Milwaukee M18 FUEL 1/2\" Impact Wrench",
                ListPrice = 379.99m,
                Discount = "B",
                Warranty = "5 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Power Tools",
                Subcategory = "Impact Tools",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Milwaukee",
                Supplier = "Milwaukee",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 18,
                Pending = 3,
                OnOrder = 10,
                Alloc = 4,
                BKO = 0,
                InTransit = 5,
                Needs = 0,
                Interests = 12,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 379.99m,
                CatalogText = "Milwaukee M18 FUEL 1/2\" high torque impact wrench. 700 ft-lbs max torque with friction ring."
            },
            new WebcatItem
            {
                Item = "MIL-2804-20",
                Description = "Milwaukee M18 FUEL Hammer Drill",
                ListPrice = 299.99m,
                Discount = "B",
                Warranty = "5 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Power Tools",
                Subcategory = "Drills",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Milwaukee",
                Supplier = "Milwaukee",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 22,
                Pending = 4,
                OnOrder = 12,
                Alloc = 5,
                BKO = 0,
                InTransit = 6,
                Needs = 0,
                Interests = 15,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 299.99m,
                CatalogText = "M18 FUEL 1/2\" hammer drill/driver. Brushless motor delivers 1,200 in-lbs of torque."
            },
            new WebcatItem
            {
                Item = "MIL-2997-22",
                Description = "Milwaukee M18 FUEL 2-Tool Combo Kit",
                ListPrice = 499.99m,
                Discount = "C",
                Warranty = "5 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Power Tools",
                Subcategory = "Drills",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Milwaukee",
                Supplier = "Milwaukee",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 14,
                Pending = 2,
                OnOrder = 8,
                Alloc = 3,
                BKO = 0,
                InTransit = 4,
                Needs = 0,
                Interests = 10,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 499.99m,
                CatalogText = "M18 FUEL 2-tool combo kit. Includes hammer drill, impact driver, 2 batteries, and charger."
            },

            // Power Tools - DeWalt Brand
            new WebcatItem
            {
                Item = "DWT-DCF899B",
                Description = "DeWalt 20V MAX 1/2\" Impact Wrench",
                ListPrice = 329.99m,
                Discount = "B",
                Warranty = "3 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Power Tools",
                Subcategory = "Impact Tools",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "DeWalt",
                Supplier = "DeWalt",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 25,
                Pending = 5,
                OnOrder = 15,
                Alloc = 6,
                BKO = 0,
                InTransit = 8,
                Needs = 0,
                Interests = 18,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 329.99m,
                CatalogText = "DeWalt 20V MAX XR brushless 1/2\" impact wrench. 700 ft-lbs max torque."
            },
            new WebcatItem
            {
                Item = "DWT-DCD996B",
                Description = "DeWalt 20V MAX XR Hammer Drill",
                ListPrice = 259.99m,
                Discount = "B",
                Warranty = "3 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Power Tools",
                Subcategory = "Drills",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "DeWalt",
                Supplier = "DeWalt",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 28,
                Pending = 4,
                OnOrder = 12,
                Alloc = 7,
                BKO = 0,
                InTransit = 6,
                Needs = 0,
                Interests = 16,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 259.99m,
                CatalogText = "DeWalt 20V MAX XR brushless hammer drill. 3-speed transmission delivers 820 in-lbs."
            },
            new WebcatItem
            {
                Item = "DWT-DCK2100P2",
                Description = "DeWalt 20V MAX 2-Tool Combo Kit",
                ListPrice = 449.99m,
                Discount = "C",
                Warranty = "3 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Power Tools",
                Subcategory = "Drills",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "DeWalt",
                Supplier = "DeWalt",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 16,
                Pending = 3,
                OnOrder = 8,
                Alloc = 4,
                BKO = 0,
                InTransit = 4,
                Needs = 0,
                Interests = 11,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 449.99m,
                CatalogText = "DeWalt 20V MAX 2-tool combo. Includes drill/driver, impact driver, 2 batteries, and charger."
            },

            // Diagnostics - Bosch Brand
            new WebcatItem
            {
                Item = "BOSCH-ADS625",
                Description = "Bosch ADS 625 Diagnostic Scan Tool",
                ListPrice = 2799.99m,
                Discount = "TECH",
                Warranty = "2 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Diagnostics",
                Subcategory = "Scanners",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Bosch",
                Supplier = "Bosch",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 5,
                Pending = 1,
                OnOrder = 2,
                Alloc = 1,
                BKO = 0,
                InTransit = 1,
                Needs = 0,
                Interests = 4,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 2799.99m,
                CatalogText = "Bosch ADS 625 professional diagnostic scan tool with 10\" touchscreen."
            },

            // Diagnostics - Cornwell/Partner Brands
            new WebcatItem
            {
                Item = "SCAN5500",
                Description = "Professional Diagnostic Scanner",
                ListPrice = 3299.99m,
                Discount = "TECH",
                Warranty = "2 Year",
                Action = "Limited Warranty",
                Status = "Active",
                IsPriceConfirm = true,
                Category = "Diagnostics",
                Subcategory = "Scanners",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 4,
                Pending = 1,
                OnOrder = 2,
                Alloc = 1,
                BKO = 0,
                InTransit = 1,
                Needs = 0,
                Interests = 3,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 3299.99m,
                CatalogText = "Professional-grade OBD-II diagnostic scanner with bi-directional controls and advanced features."
            },
            new WebcatItem
            {
                Item = "MM500",
                Description = "Digital Multimeter Pro",
                ListPrice = 189.99m,
                Discount = "A",
                Warranty = "3 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Diagnostics",
                Subcategory = "Meters",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 23,
                Pending = 4,
                OnOrder = 10,
                Alloc = 5,
                BKO = 0,
                InTransit = 5,
                Needs = 0,
                Interests = 8,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 189.99m,
                CatalogText = "Professional digital multimeter with auto-ranging and true RMS."
            },

            // Fluke Brand Meters
            new WebcatItem
            {
                Item = "FLUKE-87V",
                Description = "Fluke 87V Industrial Multimeter",
                ListPrice = 449.99m,
                Discount = "TECH",
                Warranty = "Lifetime",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Diagnostics",
                Subcategory = "Meters",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Fluke",
                Supplier = "Fluke",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 12,
                Pending = 2,
                OnOrder = 5,
                Alloc = 3,
                BKO = 0,
                InTransit = 2,
                Needs = 0,
                Interests = 7,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 449.99m,
                CatalogText = "Fluke 87V true-RMS industrial multimeter. Best-in-class accuracy and reliability."
            },

            // Local Only Items (LPN- prefix)
            new WebcatItem
            {
                Item = "LPN-FILTER01",
                Description = "Oil Filter - Universal Fit",
                ListPrice = 12.99m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "No Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Extensions",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 45,
                Pending = 0,
                OnOrder = 0,
                Alloc = 8,
                BKO = 0,
                InTransit = 0,
                Needs = 12,
                Interests = 15,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 12.99m,
                CatalogText = "Universal oil filter suitable for most domestic vehicles."
            },
            new WebcatItem
            {
                Item = "LPN-AIRGUN",
                Description = "Air Gun Blow Off Nozzle",
                ListPrice = 19.99m,
                Discount = "A",
                Warranty = "90 Days",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Generic",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 28,
                Pending = 0,
                OnOrder = 0,
                Alloc = 5,
                BKO = 0,
                InTransit = 0,
                Needs = 8,
                Interests = 12,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 19.99m,
                CatalogText = "Heavy-duty blow off air gun with safety nozzle."
            },
            new WebcatItem
            {
                Item = "LPN-GLOVES",
                Description = "Mechanic Gloves - Large",
                ListPrice = 24.99m,
                Discount = "A",
                Warranty = "No Warranty",
                Action = "No Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Extensions",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Mechanix Wear",
                Supplier = "Local",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 36,
                Pending = 0,
                OnOrder = 0,
                Alloc = 6,
                BKO = 0,
                InTransit = 0,
                Needs = 15,
                Interests = 20,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 24.99m,
                CatalogText = "Professional mechanic gloves with reinforced palms and fingertips."
            },

            // Discontinued items (Local Only)
            new WebcatItem
            {
                Item = "LPN-OLD01",
                Description = "Legacy Socket Set 15pc (Discontinued)",
                ListPrice = 149.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Discontinued",
                IsDiscontinued = true,
                Category = "Hand Tools",
                Subcategory = "Sockets",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                ReplacedBy = "S38SET-42",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 2,
                Pending = 0,
                OnOrder = 0,
                Alloc = 0,
                BKO = 0,
                InTransit = 0,
                Needs = 0,
                Interests = 0,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 149.99m,
                CatalogText = "DISCONTINUED - Replaced by S38SET-42"
            },
            new WebcatItem
            {
                Item = "LPN-OLD02",
                Description = "Legacy Wrench 15mm (Discontinued)",
                ListPrice = 29.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Discontinued",
                IsDiscontinued = true,
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "Local Only",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 0,
                Pending = 0,
                OnOrder = 0,
                Alloc = 0,
                BKO = 0,
                InTransit = 0,
                Needs = 0,
                Interests = 0,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 29.99m,
                CatalogText = "DISCONTINUED - No replacement available"
            },

            // Special Order items
            new WebcatItem
            {
                Item = "TQ-DIGITAL",
                Description = "Digital Torque Wrench 1/2\" Drive",
                ListPrice = 549.99m,
                Discount = "TECH",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                IsSpecialOrder = true,
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 0,
                Pending = 0,
                OnOrder = 0,
                Alloc = 0,
                BKO = 0,
                InTransit = 0,
                Needs = 0,
                Interests = 2,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 549.99m,
                CatalogText = "Special order digital torque wrench. 10-150 ft-lbs range with LCD display."
            },
            new WebcatItem
            {
                Item = "EXT-LONG",
                Description = "Extra Long Extension Set 3pc",
                ListPrice = 79.99m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Drive Tools",
                Subcategory = "Extensions",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 0,
                Pending = 0,
                OnOrder = 25,
                Alloc = 0,
                BKO = 12,
                InTransit = 0,
                Needs = 12,
                Interests = 8,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 79.99m,
                CatalogText = "3-piece extra long extension set. Currently on backorder."
            },

            // Additional realistic items - Cornwell Tools
            new WebcatItem
            {
                Item = "SD-SET20",
                Description = "Screwdriver Set 20pc Professional",
                ListPrice = 124.99m,
                Discount = "B",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                IsPriceConfirm = true,
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 28,
                Pending = 5,
                OnOrder = 15,
                Alloc = 6,
                BKO = 0,
                InTransit = 8,
                Needs = 0,
                Interests = 11,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 124.99m,
                CatalogText = "Professional 20-piece screwdriver set with Phillips, flathead, and Torx drivers."
            },
            new WebcatItem
            {
                Item = "PL-SET5",
                Description = "Pliers Set 5pc Professional",
                ListPrice = 159.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 22,
                Pending = 4,
                OnOrder = 10,
                Alloc = 5,
                BKO = 0,
                InTransit = 5,
                Needs = 0,
                Interests = 9,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 159.99m,
                CatalogText = "Professional 5-piece pliers set including needle nose, slip joint, and diagonal cutters."
            },
            new WebcatItem
            {
                Item = "1040305331",
                Description = "Precision Measurement Tool Set",
                ListPrice = 749.99m,
                Discount = "TECH",
                Warranty = "1 Year",
                Action = "Limited Warranty",
                Status = "Active",
                IsCSI = true,
                Category = "Diagnostics",
                Subcategory = "Meters",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 7,
                Pending = 1,
                OnOrder = 3,
                Alloc = 2,
                BKO = 0,
                InTransit = 1,
                Needs = 0,
                Interests = 4,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 749.99m,
                CatalogText = "Complete precision measurement tool set including calipers, micrometers, and depth gauges."
            },
            new WebcatItem
            {
                Item = "10995DI",
                Description = "Digital Inspection Camera",
                ListPrice = 599.99m,
                Discount = "TECH",
                Warranty = "2 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Diagnostics",
                Subcategory = "Scanners",
                Class = "CQT Stock",
                ShipFrom = "2DC",
                Brand = "Cornwell Quality Tools",
                Supplier = "CQT",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 11,
                Pending = 2,
                OnOrder = 5,
                Alloc = 3,
                BKO = 0,
                InTransit = 2,
                Needs = 0,
                Interests = 6,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 599.99m,
                CatalogText = "High-definition digital inspection camera with 5-inch display and flexible probe."
            },

            // Makita Power Tools
            new WebcatItem
            {
                Item = "MAK-XWT11Z",
                Description = "Makita 18V LXT Impact Wrench 1/2\"",
                ListPrice = 349.99m,
                Discount = "B",
                Warranty = "3 Year",
                Action = "Limited Warranty",
                Status = "Active",
                Category = "Power Tools",
                Subcategory = "Impact Tools",
                Class = "CQT Stock",
                ShipFrom = "1DC",
                Brand = "Makita",
                Supplier = "Makita",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 14,
                Pending = 2,
                OnOrder = 8,
                Alloc = 3,
                BKO = 0,
                InTransit = 4,
                Needs = 0,
                Interests = 9,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 349.99m,
                CatalogText = "Makita 18V LXT brushless 1/2\" impact wrench. 560 ft-lbs max torque."
            },

            // Knipex Pliers
            new WebcatItem
            {
                Item = "KNIPEX-8701",
                Description = "Knipex Cobra Pliers 10\"",
                ListPrice = 54.99m,
                Discount = "A",
                Warranty = "Lifetime",
                Action = "Full Warranty",
                Status = "Active",
                Category = "Hand Tools",
                Subcategory = "Wrenches",
                Class = "CQT Stock",
                ShipFrom = "CQT",
                Brand = "Knipex",
                Supplier = "Knipex",
                BuyQty = 1,
                SellQty = 1,
                OnHand = 32,
                Pending = 5,
                OnOrder = 15,
                Alloc = 8,
                BKO = 0,
                InTransit = 7,
                Needs = 0,
                Interests = 14,
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 54.99m,
                CatalogText = "Knipex Cobra high-tech water pump pliers. 10\" length with push-button adjustment."
            }
        };

        // Add more items with variety (increase to 40 generated items)
        for (int i = 1; i <= 40; i++)
        {
            // Determine class - 75% CQT Stock, 25% Local Only
            var itemClass = random.Next(0, 4) < 3 ? "CQT Stock" : "Local Only";
            var itemPrefix = itemClass == "Local Only" ? "LPN-WEB" : "12LSTR";

            // Vary brands based on category
            var brands = new[] { "Cornwell Quality Tools", "Milwaukee", "DeWalt", "Bosch", "Makita", "Knipex" };
            var selectedBrand = itemClass == "Local Only" ? "Generic" : brands[random.Next(brands.Length)];

            // Vary categories
            var categories = new[] { "Hand Tools", "Drive Tools", "Power Tools", "Diagnostics" };
            var selectedCategory = categories[random.Next(categories.Length)];

            // Vary subcategories based on category
            var subcategory = selectedCategory switch
            {
                "Hand Tools" => new[] { "Wrenches", "Sockets", "Extensions" }[random.Next(3)],
                "Drive Tools" => new[] { "3/8\" Ratchets", "1/2\" Ratchets", "Extensions" }[random.Next(3)],
                "Power Tools" => new[] { "Drills", "Impact Tools" }[random.Next(2)],
                "Diagnostics" => new[] { "Scanners", "Meters" }[random.Next(2)],
                _ => "Wrenches"
            };

            items.Add(new WebcatItem
            {
                Item = $"{itemPrefix}{i:D3}",
                Description = selectedCategory == "Hand Tools"
                    ? $"Socket 12pt {10 + i}mm"
                    : $"{selectedCategory.Replace(" Tools", "")} Tool Item {i}",
                ListPrice = 15.99m + i * 2.50m,
                Discount = new[] { "A", "B", "C", "TECH" }[random.Next(4)],
                Warranty = selectedBrand == "Cornwell Quality Tools" || selectedBrand == "Knipex" ? "Lifetime" : $"{random.Next(1, 6)} Year",
                Action = selectedBrand == "Cornwell Quality Tools" || selectedBrand == "Knipex" ? "Full Warranty" : "Limited Warranty",
                Status = random.Next(0, 15) < 14 ? "Active" : "Discontinued",
                IsDiscontinued = random.Next(0, 15) >= 14,
                Category = selectedCategory,
                Subcategory = subcategory,
                Class = itemClass,
                ShipFrom = new[] { "CQT", "1DC", "2DC", "3DC" }[random.Next(4)],
                Brand = selectedBrand,
                Supplier = selectedBrand == "Generic" ? "Local" : selectedBrand,
                BuyQty = 1,
                SellQty = 1,
                OnHand = random.Next(0, 120),
                Pending = random.Next(0, 15),
                OnOrder = random.Next(0, 40),
                Alloc = random.Next(0, 20),
                BKO = random.Next(0, 8),
                InTransit = random.Next(0, 25),
                Needs = random.Next(0, 15),
                Interests = random.Next(0, 25),
                EffectiveDate = new DateTime(2025, 7, 10),
                LocalListPrice = 15.99m + i * 2.50m,
                CatalogText = $"{selectedBrand} {selectedCategory.ToLower()} item. Professional quality construction."
            });
        }

        return items;
    }

    public sealed class WebcatItem
    {
        public string Item { get; set; } = "";
        public string Description { get; set; } = "";
        public decimal ListPrice { get; set; }
        public string Discount { get; set; } = "A";
        public string Warranty { get; set; } = "";
        public string Action { get; set; } = "";
        public string Status { get; set; } = "";
        public string Category { get; set; } = "";
        public string Subcategory { get; set; } = "";
        public string Class { get; set; } = "";
        public string ShipFrom { get; set; } = "";
        public string Brand { get; set; } = "";
        public string Supplier { get; set; } = "";
        public string ReplacedBy { get; set; } = "";
        public int BuyQty { get; set; }
        public int SellQty { get; set; }

        public int OnHand { get; set; }
        public int Pending { get; set; }
        public int OnOrder { get; set; }
        public int Alloc { get; set; }
        public int BKO { get; set; }
        public int InTransit { get; set; }
        public int Needs { get; set; }
        public int Interests { get; set; }

        public DateTime? EffectiveDate { get; set; }
        public decimal LocalListPrice { get; set; }
        public string CatalogText { get; set; } = "";

        public bool IsDiscontinued { get; set; }
        public bool IsPriceConfirm { get; set; }
        public bool IsCSI { get; set; }
        public bool IsDropShip { get; set; }
        public bool IsSpecialOrder { get; set; }
    }
}